from __future__ import annotations

import re
from typing import Sequence

import numpy as np
import pandas as pd

from .sentiment import BaseSentimentModel


POSITIVE_WORDS: frozenset[str] = frozenset({
    "able", "abundance", "abundant", "accomplish", "accomplished",
    "accomplishment", "achieve", "achieved", "achievement", "acquire",
    "advance", "advanced", "advancement", "advantage", "advantageous",
    "affluent", "alleviate", "alliance", "appreciable", "appreciate",
    "appreciated", "approve", "approved", "astute", "attain", "attractive",
    "award", "awarded", "beneficial", "benefited", "benefit", "benefits",
    "best", "better", "boom", "booming", "boost", "boosted", "breakthrough",
    "brilliant", "build", "capable", "capacity", "capitalize", "celebrate",
    "certain", "certainty", "champion", "clarity", "collaborate",
    "collaboration", "commit", "commits", "committed", "commitment",
    "compelling", "competitive", "competitiveness", "complement",
    "complementary", "compliance", "compliant", "confidence", "confident",
    "consistency", "consistent", "constructive", "contribution",
    "cooperation", "cooperative", "correct", "creative", "credibility",
    "credible", "deal", "decent", "decisive", "dedicated", "dedication",
    "definitely", "definitive", "delight", "demand", "dependable",
    "deserve", "desired", "determination", "determined", "develop",
    "developed", "development", "devoted", "diligence", "diligent",
    "discipline", "disciplined", "discover", "discovery",
    "distinct", "distinction", "distinctive", "distinguish",
    "distinguished", "diverse", "diversified", "diversity", "dominant",
    "dominate", "drive", "driven", "dynamic", "eager", "earn", "earned",
    "earnings", "economic", "economical", "economies", "economy",
    "effective", "effectiveness", "efficiency", "efficient",
    "elevate", "eligible", "embrace", "emerge", "emerged", "emergence",
    "empower", "empowered", "empowerment", "enable", "enabled",
    "encourage", "encouraged", "encouragement", "endorse", "endorsed",
    "endorsement", "energetic", "energy", "engage", "engaged",
    "engagement", "engaging", "enhance", "enhanced", "enhancement",
    "enjoy", "enjoyment", "enormous", "enterprising",
    "enthusiasm", "enthusiastic", "entitled", "entrepreneur",
    "entrepreneurial", "equitable", "equity", "essential", "ethical",
    "evolve", "evolved", "evolution", "exceed", "exceeded", "exceeding",
    "excellence", "excellent", "exceptional", "exclusive", "exemplary",
    "expand", "expanded", "expanding", "expansion",
    "expedite", "expert", "expertise", "explicit",
    "exploration", "explore", "extend", "extended", "extension",
    "extraordinary", "facilitate", "facilitated", "fair", "fairly",
    "fairness", "faith", "favorable", "favorably", "favored",
    "feasible", "fidelity", "fiduciary", "financially",
    "flexibility", "flexible", "flourish", "flourishing", "focus",
    "focused", "forecast", "formidable",
    "fortunate", "franchise", "free", "freedom",
    "fruitful", "fulfill", "fulfilled", "fulfillment",
    "gain", "gained", "gaining", "gains", "generate",
    "generation", "generous", "genuine",
    "goal", "good", "goodwill", "governance",
    "great", "greatest", "grew", "groundbreaking",
    "grow", "growing", "grown", "growth", "guarantee", "guaranteed",
    "guidance", "happiness", "happy",
    "healthy", "heightened", "helpful", "heritage",
    "honest", "honesty", "honor", "honored", "hope", "hopeful",
    "huge", "ideal", "impact", "imperative",
    "importance", "important", "impressive",
    "improve", "improved", "improvement", "improvements", "improving",
    "incentive", "incentives", "increase", "increased", "increasing",
    "independent", "indispensable",
    "influence", "influential", "informative",
    "ingenuity", "initiate", "initiative", "initiatives",
    "innovate", "innovation", "innovations", "innovative",
    "insight", "insightful", "inspired", "inspiring",
    "integral", "integrate", "integrated", "integration", "integrity",
    "intellectual", "intelligence", "intelligent",
    "interest", "interested", "interesting",
    "invest", "investment", "investments", "investor", "investors",
    "invigorate", "keen", "key",
    "knowledge", "knowledgeable", "landmark",
    "launch", "launched", "lead", "leader", "leadership", "leading",
    "learn", "learning", "legacy", "legal",
    "leverage", "leveraged", "liquidity",
    "long-term", "loyal", "loyalty", "lucrative",
    "maintain", "maintained", "maintenance", "major",
    "manageable", "management", "manager", "managerial",
    "margin", "market", "marketable", "massive",
    "mature", "maturity", "maximize", "meaningful",
    "mentor", "merit", "meticulous", "milestone",
    "minimize", "mission", "momentum",
    "monetary", "monitor", "morale", "motivate", "motivated", "motivation",
    "mutual", "necessary",
    "negotiate", "negotiated", "negotiation",
    "network", "notable", "notably", "notice",
    "nurture", "objective",
    "obtain", "obtained", "offer", "offering",
    "open", "openly", "operate", "operational",
    "opportunity", "optimism", "optimistic",
    "organization", "organizational", "organized",
    "outcome", "outperform", "outperformed", "outstanding",
    "ownership", "partnership",
    "passion", "passionate", "patience", "patient",
    "peak", "penetration",
    "perform", "performance", "performed", "performing",
    "perseverance", "persist", "persistence", "persistent",
    "pioneer", "pioneering",
    "pleased", "pledge", "plentiful",
    "poised", "popular", "popularity",
    "position", "positioned", "positive", "positively",
    "possibility", "possible", "potential",
    "power", "powerful", "practical", "pragmatic",
    "predictable", "preeminent",
    "prefer", "preferable", "preference", "preferred", "premier",
    "premium", "prepared", "preparedness", "presence",
    "prestige", "prestigious", "prevail",
    "prevalent", "prevent", "prevented", "prevention",
    "price", "pride", "primary", "prime",
    "principal", "principle", "principled",
    "proactive", "proceeds",
    "produce", "produced", "producer", "product",
    "production", "productive", "productivity",
    "professional", "professionalism", "proficiency",
    "profit", "profitability", "profitable", "profits",
    "program", "progress", "progressive",
    "project", "projection", "prominence", "prominent",
    "promising", "promote", "promoted", "promotion",
    "proper", "property", "proposal", "propose", "proposed",
    "prosper", "prosperity", "prosperous",
    "protect", "protected", "protection", "protective",
    "proven", "provide", "provided", "provider",
    "prudence", "prudent", "purchase", "purchased",
    "pursue", "pursuit", "qualify", "quality",
    "rapid", "rapidly", "reach", "reached",
    "readily", "ready", "realistic", "realize", "realized",
    "reasonable", "reasonably", "rebound",
    "receptive", "recognition", "recognize", "recognized",
    "recommend", "recommendation", "recommended",
    "record", "recover", "recovered", "recovery",
    "recruit", "recruitment", "rectify",
    "redemption", "reduce", "reduced", "reduction",
    "reform", "refresh", "refund", "refurbish",
    "regain", "regional",
    "registered", "registration",
    "regulate", "regulated", "regulation", "regulatory",
    "rehabilitate", "rehabilitation",
    "reinforce", "reinforced", "reinstate",
    "reiterate", "relate", "related",
    "relationship", "relative", "release",
    "relevance", "relevant", "reliability", "reliable",
    "relief", "relieve", "relocate",
    "remain", "remains", "remedy",
    "renew", "renewable", "renewed", "renovate",
    "renowned", "reopen", "reorganization",
    "repair", "repayment", "repeat",
    "replace", "replacement", "replenish",
    "report", "reported", "reporting",
    "represent", "representation", "representative",
    "reputation", "request",
    "require", "required", "requirement",
    "rescue", "research",
    "reserve", "reserved", "reserves",
    "resilience", "resilient", "resist", "resistance",
    "resolution", "resolve", "resolved",
    "resource", "resources", "respect",
    "respond", "response", "responsibility", "responsible",
    "restoration", "restore", "restored",
    "restructure", "restructured", "restructuring",
    "result", "resume", "retail",
    "retain", "retained", "retention",
    "retire", "retired", "retirement",
    "return", "returned", "returns",
    "reveal", "revealed", "revenue", "revenues",
    "reverse", "review", "reviewed",
    "revise", "revised", "revision",
    "revitalize", "revitalized", "revival",
    "reward", "rewarded", "rewarding",
    "rich", "right", "rights",
    "rise", "rising", "robust", "robustness",
    "safeguard", "safeguarded", "safety",
    "sale", "sales", "salutary",
    "satisfaction", "satisfactory", "satisfied",
    "save", "saving", "savings",
    "scale", "scalable", "schedule",
    "secure", "secured", "securely", "security",
    "seek", "seeking",
    "select", "selected", "selection", "selective",
    "senior", "sense",
    "serve", "served", "service", "services", "serving",
    "settle", "settled", "settlement",
    "share", "shared", "shareholder",
    "sharp", "significant", "significantly",
    "simplify", "skilled",
    "smart", "smooth", "soar", "soaring",
    "social", "solid", "solution", "solve", "solved",
    "sophisticated", "sound", "source",
    "special", "specialist", "specialized",
    "specific", "specifically", "speed",
    "stability", "stabilize", "stabilized", "stable",
    "staff", "stake", "stakeholder", "stakeholders",
    "standard", "standards", "standing",
    "start", "startup", "state", "stated",
    "steadfast", "steady", "stellar",
    "stewardship", "stimulate", "stimulus",
    "strategic", "strategically", "strategy",
    "streamline", "streamlined",
    "strength", "strengthen", "strengthened", "strengthening",
    "strong", "stronger", "strongly",
    "structural", "structure", "structured",
    "study", "substantial", "substantially",
    "succeed", "succeeded", "success", "successful",
    "successfully", "sufficient",
    "suggest", "suggested", "suggestion",
    "suitable", "summary", "summit",
    "super", "superb", "superior", "superiority",
    "supplement", "supplemental",
    "supplier", "suppliers", "supply", "support",
    "supported", "supporting", "supportive",
    "supreme", "sure", "surge", "surpassed",
    "surplus", "sustainability", "sustainable", "sustained",
    "synergistic", "synergy",
    "system", "systematic",
    "tackle", "tactical", "tailor", "tailored",
    "talent", "talented", "tangible",
    "target", "targeted", "task",
    "team", "teamwork", "technical", "technique", "technology",
    "tenacious", "tenacity",
    "test", "testament", "testimony",
    "thank", "thorough", "thoughtful",
    "threshold", "thrift", "thrive", "thrived", "thriving",
    "timely", "timing",
    "tolerable", "tolerance", "tolerant",
    "top", "total", "touch",
    "track", "tracking", "trade",
    "trading", "tradition", "traditional",
    "train", "trained", "training",
    "transaction", "transfer",
    "transform", "transformation", "transformed", "transformative",
    "transition", "transparency", "transparent",
    "transportation", "treasury",
    "treat", "treated", "treatment",
    "tremendous", "trend", "trigger",
    "trim", "triumph",
    "trust", "trusted", "trustee", "trustworthy",
    "truth", "turnaround",
    "ultimate", "ultimately",
    "unanimous", "unbiased", "uncover",
    "understand", "understanding", "undertake", "undertaken", "undertaking",
    "underway", "underwrite", "underwriting",
    "undoubtedly", "unemployed", "unemployment",
    "unified", "uniform", "unique", "unite", "united", "unity",
    "universal", "unlike", "unlikely",
    "unprecedented", "unquestionable",
    "upbeat", "update", "updated",
    "upgrade", "upgraded", "upgrading",
    "upheld", "upside", "upward",
    "urgent", "useful",
    "utility", "utilize", "utilized",
    "valid", "validate", "validated", "validation", "validity",
    "valuable", "valuation", "value", "valued", "values",
    "vanguard", "variety", "vast",
    "venture", "versatile", "versatility", "vertical",
    "viability", "viable", "vibrant",
    "victory", "vigilant", "vigor", "vigorous",
    "virtue", "vision", "visionary",
    "vital", "vitality", "vivid",
    "voice", "volume", "voluntary", "vote",
    "warrant", "warranty",
    "wealth", "wealthy", "welcome", "welcomed",
    "well", "wellness", "wellbeing",
    "widespread", "willing", "willingness",
    "win", "winner", "winning",
    "wisdom", "wise", "withdraw", "withdrawal",
    "witness", "wonder", "wonderful",
    "work", "workable", "worker", "workforce", "working",
    "workplace", "works", "workshop",
    "world", "worldwide", "worth", "worthwhile", "worthy",
    "write", "yield", "yielding",
    "young",
})

NEGATIVE_WORDS: frozenset[str] = frozenset({
    "abandon", "abandoned", "abandonment", "abdicate",
    "aberration", "abnormal", "abolish", "abominable",
    "abrasive", "abrogate", "abrupt", "abruptly",
    "abscond", "absence", "absent", "absenteeism",
    "absolve", "abstain", "abstention", "abstinence",
    "absurd", "absurdity", "abuse", "abused", "abusive",
    "abysmal", "abyss", "accident", "accidental",
    "accusation", "accuse", "accused",
    "ache", "acknowledge",
    "acquiesce", "acquit", "acquittal",
    "adamant", "addict", "addicted", "addiction",
    "adjourn", "adjudicate", "adjudication",
    "admonish", "admonition",
    "adverse", "adversely", "adversity",
    "affidavit", "afflict", "afflicted", "affliction",
    "aftermath", "aggravate", "aggravated", "aggravation",
    "aggression", "aggressive", "aggressively",
    "aggrieved", "agitate", "agitated", "agitation",
    "agonizing", "ailing", "ailment",
    "alarming", "alert",
    "alienate", "alienated", "alienation",
    "allegation", "allege", "alleged", "allegedly",
    "altercation", "amalgamation",
    "amend", "amended", "amendment",
    "animosity", "annihilate",
    "annoy", "annoyance", "anomaly",
    "antagonism", "antagonistic",
    "antitrust", "anxiety", "anxious",
    "apathy", "appall", "appalling",
    "appeal", "appellant", "appellate",
    "apprehend", "apprehension", "apprehensive",
    "arbitrary", "arbitrate", "arbitration", "arbitrator",
    "arduous", "argument",
    "arraign", "arraignment", "arrears",
    "arrest", "arrogant", "arson",
    "assail", "assault",
    "assert", "assertion",
    "attrition", "audacious",
    "averse", "aversion", "avert",
    "avoid", "avoidance",
    "backlash", "backlog", "backward",
    "bad", "badly", "baffle",
    "bail", "balloon", "ballot",
    "ban", "bandit", "bankrupt", "bankruptcy",
    "bar", "bare", "barely", "barrage", "barrier",
    "battle", "bear", "bearer",
    "belittle", "bereavement", "bereft",
    "beset", "besiege", "betray", "betrayal",
    "bias", "biased",
    "blacklist", "blame", "bland",
    "blast", "blatant", "bleak", "blemish",
    "blight", "bloated", "block", "blockade",
    "blow", "blunder", "blunt", "blur",
    "bogus", "bomb", "bondage",
    "bore", "boredom", "borrow",
    "bottleneck", "bottom",
    "boycott", "breach", "breakdown",
    "bribe", "bribery", "brink",
    "broken", "brutal", "brutality",
    "bubble", "bug", "bulk",
    "bullish", "bully", "bump",
    "burden", "burdensome",
    "bureaucracy", "bureaucratic", "burglary",
    "burn", "burst", "bust",
    "calamity", "cancel", "cancellation",
    "capitulate", "capitulation", "capsize",
    "captive", "capture",
    "careless", "cartel",
    "casualty", "catastrophe", "catastrophic",
    "caution", "cautionary", "cautious", "caveat",
    "cease", "censure",
    "challenge", "challenged", "challenging",
    "chaos", "chaotic",
    "charge", "cheap", "cheapen",
    "choke", "chronic",
    "circumvent", "claim", "claimant",
    "clandestine", "clash",
    "clean", "clearance",
    "coerce", "coercion", "coercive",
    "collapse", "collateral",
    "collide", "collision",
    "collude", "collusion",
    "combat",
    "commandeer",
    "complacent", "complacence",
    "complain", "complaint",
    "complicate", "complicated", "complication",
    "complicit",
    "compromise",
    "compulsion", "compulsory",
    "conceal", "concede",
    "concern", "concerned", "concerning",
    "concession",
    "condemn", "condemnation", "condescending",
    "condition", "conditional",
    "condone", "confess", "confession",
    "confine", "confined", "confinement",
    "confiscate", "confiscation",
    "conflict", "confound",
    "confront", "confrontation",
    "confuse", "confused", "confusing", "confusion",
    "congested", "congestion",
    "conjecture",
    "connive",
    "conquer", "conscience",
    "consent",
    "consequence", "consequent", "consequential",
    "conservative",
    "conspicuous", "conspiracy", "conspire",
    "constrain", "constrained", "constraint",
    "constrict", "constriction",
    "contagious", "contaminate", "contamination",
    "contemplate",
    "contempt", "contend", "contender",
    "contention", "contentious",
    "contest", "contestant", "contestation",
    "contingency", "contingent",
    "contort",
    "contract", "contractor",
    "contradict", "contradiction", "contradictory",
    "contrary",
    "controversial", "controversy",
    "convene",
    "convict", "conviction",
    "corrode", "corrosion", "corrosive",
    "corrupt", "corrupted", "corruption",
    "costly", "counterfeit",
    "counterproductive",
    "coup", "crack", "crackdown",
    "crash", "grave", "crazy",
    "creditor",
    "creep", "crime", "criminal",
    "cripple", "crippling", "crisis",
    "critic", "critical", "criticism", "criticize",
    "crumble", "crunch", "crush",
    "culpable", "culprit",
    "curtail", "curtailment",
    "custody", "cut", "cutback", "cuthroat",
    "damage", "damaged", "damages", "damaging",
    "dampen", "danger", "dangerous",
    "dash", "daunting",
    "dead", "deadline", "deadlock", "deadly",
    "deaf", "dearth",
    "death", "debacle", "debase",
    "debatable", "debate", "debris",
    "debt", "debtor",
    "decay", "decease", "deceit", "deceitful",
    "deceive", "decelerate",
    "deception", "deceptive",
    "declaration", "declare",
    "decline", "declining",
    "decrease", "decreased", "decreasing",
    "decree",
    "deduct", "deduction",
    "deem", "deemed",
    "defamation", "defamatory",
    "default", "defeat",
    "defect", "defective",
    "defendant", "defender",
    "defer", "deference", "deferral", "deferred",
    "defiance", "deficiency", "deficient", "deficit",
    "deflate", "deflation",
    "defraud", "defunct", "defy",
    "degenerate", "degradation", "degrade", "degraded",
    "delay", "delayed",
    "delegate", "delegation",
    "delete", "deleterious",
    "deliberate", "deliberately", "deliberation",
    "delinquency", "delinquent",
    "delude", "deluge", "delusion",
    "demand", "demanding",
    "demise", "demolish", "demolition",
    "demoralize", "demote",
    "denial", "denounce",
    "dent", "deny",
    "depart", "departure",
    "depend", "dependence", "dependent",
    "deplete", "depleted", "depletion",
    "deplore", "deploy", "deployment",
    "depopulate", "depopulation",
    "deport", "deportation",
    "depose", "deposit", "deposition",
    "depreciate", "depreciation",
    "depress", "depressed", "depressing", "depression",
    "deprivation", "deprive", "deprived",
    "derail", "derelict", "dereliction",
    "deride", "derivative",
    "derogatory", "descend", "descendant",
    "desecrate", "desert",
    "desolate", "despair",
    "desperate", "desperately", "desperation",
    "despise", "despondent",
    "destabilize", "destitute",
    "destroy", "destroyed", "destruction", "destructive",
    "detach", "detached", "detachment",
    "detain", "detection", "detention",
    "deter", "deteriorate", "deterioration",
    "determination", "determine", "determined",
    "deterrent", "detest",
    "detract", "detriment", "detrimental",
    "devastate", "devastating", "devastation",
    "deviate", "deviation",
    "devoid", "devour",
    "diagnose", "diagnosis",
    "dictate", "die",
    "differ", "difference", "different",
    "difficult", "difficulty",
    "dilapidated", "dilemma",
    "dilute", "dilution",
    "dim", "diminish", "diminished", "diminution",
    "dip", "disability", "disable", "disabled",
    "disadvantage", "disadvantaged", "disadvantageous",
    "disaffect", "disagree", "disagreeable", "disagreement",
    "disallow", "disappear", "disappearance",
    "disappoint", "disappointed", "disappointing", "disappointment",
    "disapproval", "disapprove",
    "disarm", "disarmament", "disarray",
    "disaster", "disastrous",
    "disburse", "disbursement",
    "discard", "discern",
    "discharge", "disclaim", "disclaimer",
    "disclose", "disclosed", "disclosure",
    "discomfort", "disconnect", "discontent",
    "discontinuance", "discontinue", "discontinued",
    "discount", "discountenance",
    "discourage", "discouraged",
    "discredit", "discrepancy",
    "discriminate", "discrimination", "discriminatory",
    "disdain", "disease",
    "disenfranchise", "disgrace", "disgraceful",
    "disgruntled", "disguise", "disgust", "disgusting",
    "dishonest", "dishonesty", "dishonor",
    "disillusion", "disincentive",
    "disingenuous", "disintegrate", "disintegration",
    "disinterest", "disinterested",
    "disjointed", "dislike",
    "dislocate", "dislocation", "dislodge",
    "disloyal", "dismal",
    "dismantle", "dismantled", "dismay",
    "dismiss", "dismissal", "dismissed",
    "disobedience", "disobey",
    "disorder", "disorderly",
    "disorganized", "disorient",
    "disparage", "disparate", "disparity",
    "dispatch", "dispel",
    "disperse", "displace", "displaced", "displacement",
    "display", "displease",
    "disposal", "dispose", "disposed", "disposition",
    "disproportionate", "disprove",
    "dispute", "disqualification", "disqualify",
    "disregard", "disregarded", "disreputable",
    "disrespect", "disrupt", "disrupted", "disruption", "disruptive",
    "dissatisfaction", "dissatisfied",
    "disseminate", "dissemination",
    "dissension", "dissent", "dissenter",
    "dissident", "dissipate",
    "dissolution", "dissolve",
    "distant", "distinct",
    "distort", "distorted", "distortion",
    "distract", "distracted", "distraction",
    "distraught", "distress", "distressed",
    "distrust", "disturb", "disturbance", "disturbed", "disturbing",
    "diverge", "divergence", "divergent",
    "diversion",
    "divest", "divestiture",
    "divide", "divided",
    "divorce", "divulge", "doldrums",
    "doom", "doomed", "dormant",
    "doubt", "doubtful",
    "downgrade", "downplay",
    "downright", "downside", "downsize", "downsized", "downsizing",
    "downtime", "downturn",
    "drag", "drain",
    "drastic", "drastically",
    "drawback", "drawdown",
    "dread", "dreadful",
    "dreary", "drift",
    "drop", "drought", "drown",
    "dubious", "dull", "dumb",
    "dump", "dumped", "duplicate",
    "dwindle", "dwindling",
    "ebb", "eccentric",
    "eclipse", "economize",
    "edge",
    "eliminate", "eliminated", "elimination",
    "elusive", "embargo",
    "embarrass", "embarrassed", "embarrassment",
    "embezzle", "embezzlement",
    "embitter", "embroil",
    "emergency",
    "emotional",
    "encroach", "encroachment",
    "endanger", "endangered",
    "enemy",
    "enforce", "enforceable", "enforcement",
    "enigma", "enigmatic",
    "enormity", "enormous",
    "enrage", "entangle",
    "entrench", "entrenched",
    "envy", "epidemic",
    "equivocal", "eradicate", "eradication",
    "erode", "erosion",
    "err", "errant", "erratic", "erroneous", "error",
    "erupt", "eruption",
    "escalate", "escalated", "escalation",
    "espionage", "estranged",
    "evade", "evasion", "evasive",
    "evict", "eviction",
    "evil", "exacerbate",
    "exaggerate", "exaggerated", "exaggeration",
    "exasperate",
    "exceed", "exceeding",
    "excess", "excessive", "excessively",
    "excise", "exclude", "excluded", "exclusion",
    "excruciating", "excuse",
    "exempt", "exemption",
    "exhaust", "exhausted", "exhaustion",
    "exile", "exodus",
    "exonerate", "exorbitant",
    "expedient",
    "expel", "expenditure",
    "expensive",
    "expire", "expired", "expiration",
    "explode", "exploit", "exploitation",
    "explosion", "explosive",
    "expose", "exposed", "exposure",
    "expropriate", "expropriation",
    "expulsion",
    "exterminate", "extinct", "extinction",
    "extinguish", "extortion", "extortionate",
    "extract", "extraction",
    "extradition",
    "extravagance", "extravagant",
    "extreme", "extremely", "extremist",
    "fabricate", "fabrication",
    "fade", "fail", "failed", "failing", "failure",
    "faint", "fake", "fall", "fallacy",
    "fallout", "false", "falsehood", "falsify",
    "falter", "famine",
    "farce",
    "fatal", "fatality", "fate",
    "fatigue", "fault", "faulty",
    "fear", "fearful", "fearsome",
    "feeble",
    "felony",
    "ferment", "ferocious",
    "fester", "fiasco",
    "fierce", "fight",
    "filibuster",
    "fine", "fire",
    "flagrant", "flare",
    "flat", "flatten", "flaw", "flawed",
    "flee", "flight",
    "flimsy", "flip", "float",
    "flood", "floor",
    "fluctuate", "fluctuation",
    "flurry", "foe",
    "folly", "fool", "foolish",
    "foray", "forbear", "forbearance",
    "forbid", "forbidden",
    "force", "forced", "forceful",
    "foreboding", "foreclose", "foreclosure",
    "forfeit", "forfeiture",
    "forged", "forgery",
    "forsake",
    "forthcoming",
    "foul", "founder",
    "fracture", "fragile", "fragility",
    "fragment", "fragmentation",
    "frantic", "fraud", "fraudulent",
    "fraught", "fray",
    "freeze", "frenzy",
    "friction", "fright", "frighten", "frightened",
    "frivolous",
    "frown", "frustrate", "frustrated", "frustration",
    "fugitive",
    "fumble", "fume",
    "furious", "fury",
    "fuss", "futile", "futility",
    "gag", "gainsay",
    "gall", "gamble", "gambling",
    "gap", "garbage",
    "gasp",
    "glare", "gloom", "gloomy",
    "gloss",
    "gossip",
    "graft",
    "grave", "gravity",
    "greed", "greedy",
    "grief", "grievance", "grieve", "grievous",
    "grim", "grind",
    "gripe", "grip",
    "gross", "grossly",
    "groundless",
    "grudge", "gruesome", "grueling",
    "grumble",
    "guilt", "guilty",
    "gulf", "gutter",
    "habit",
    "haggle", "hail",
    "halt", "halve",
    "hammer", "hamper", "hamstring",
    "handicap", "handicapped",
    "hang", "harass", "harassment",
    "hard", "harden", "hardship",
    "harm", "harmful", "harmless",
    "harsh", "harshly",
    "hash", "hassle",
    "haste", "hasten", "hasty",
    "hate", "hatred",
    "haul", "haunt",
    "havoc", "hazard", "hazardous",
    "hectic",
    "heighten",
    "heinous",
    "helpless",
    "hesitancy", "hesitant", "hesitate", "hesitation",
    "hide", "hideous",
    "hinder", "hindrance",
    "hijack",
    "hike",
    "hit",
    "hoard", "hoax",
    "hole", "hollow",
    "homeless",
    "hook",
    "hopeless",
    "horrible", "horrific", "horrify", "horror",
    "hostage", "hostile", "hostility",
    "hover",
    "huddle",
    "hum", "humiliate", "humiliating", "humiliation",
    "hunger", "hungry",
    "hunt", "hurdle",
    "hurricane", "hurry",
    "hurt", "hurtful",
    "hush",
    "hype", "hypocrisy", "hypocrite",
    "hysterical",
    "idle",
    "ignite", "ignorance", "ignorant", "ignore",
    "ill", "illegal", "illegality", "illegitimate",
    "illicit", "illness", "illogical",
    "illusion",
    "imbalance",
    "immature", "immaturity",
    "immoral", "immorality",
    "immune", "immunity",
    "impair", "impaired", "impairment",
    "impanel",
    "impartial",
    "impasse",
    "impatient",
    "impeach", "impeachment",
    "impede", "impediment",
    "impending",
    "imperative",
    "imperfect", "imperfection",
    "impersonal",
    "impertinent",
    "implant",
    "implicate", "implication",
    "implode",
    "implore",
    "impolite",
    "impose", "imposed", "imposition",
    "impossible", "impotent",
    "impound", "impoverish", "impoverished",
    "impractical", "imprecise",
    "imprison", "imprisonment",
    "improbable", "improper", "improperly",
    "improvident",
    "impudence", "impulsive",
    "impunity",
    "inability", "inaccessible", "inaccurate",
    "inaction", "inactive", "inactivity",
    "inadequacy", "inadequate", "inadmissible",
    "inadvertent", "inadvertently",
    "inappropriate",
    "inattention", "inattentive",
    "incapable", "incapacitate", "incapacity",
    "incarcerate", "incarceration",
    "incendiary",
    "incessant",
    "incite", "incitement",
    "incline",
    "incompatible", "incompetence", "incompetent",
    "incomplete", "incomprehensible",
    "inconceivable", "inconclusive",
    "incongruous", "inconsequential",
    "inconsiderate",
    "inconsistency", "inconsistent",
    "inconspicuous",
    "inconvenience", "inconvenient",
    "incorrect", "incorrectly",
    "incredible",
    "incredulous",
    "incriminate",
    "indebted",
    "indecency", "indecent", "indecision",
    "indefinite", "indefinitely",
    "indemnification", "indemnify", "indemnity",
    "indeterminate",
    "indict", "indictment",
    "indifference", "indifferent",
    "indignant", "indignation", "indignity",
    "indirect",
    "indiscriminate",
    "indispensable",
    "induce", "inducement",
    "indulge", "indulgence",
    "industrious",
    "ineffective", "ineffectual",
    "inefficiency", "inefficient",
    "inept", "ineptitude",
    "inequality", "inequitable", "inequity",
    "inert", "inertia",
    "inescapable",
    "inevitable", "inevitably",
    "inexcusable", "inexhaustible",
    "inexorable", "inexpensive",
    "inexperience", "inexperienced",
    "inexplicable",
    "infamous", "infamy",
    "infantile",
    "infect", "infection", "infectious",
    "inferior", "inferiority",
    "inferno",
    "infest",
    "infidelity",
    "infiltrate", "infiltration",
    "infinite", "infinitely",
    "infirm", "infirmity",
    "inflame", "inflamed", "inflammation", "inflammatory",
    "inflate", "inflated", "inflation",
    "inflexible",
    "inflict", "infliction",
    "informant",
    "infraction",
    "infringe", "infringement",
    "infuriate",
    "inhibit", "inhibition",
    "inhuman", "inhumane",
    "inject",
    "injure", "injured", "injurious", "injury",
    "injustice",
    "inmate",
    "innocence",
    "innuendo",
    "inoperative",
    "inquest",
    "inquisition",
    "insane", "insanity",
    "insatiable",
    "insecure", "insecurity",
    "insensible", "insensitive", "insensitivity",
    "insidious",
    "insignificant",
    "insincere", "insincerity",
    "insinuate",
    "insist", "insistence", "insistent",
    "insolvency", "insolvent",
    "insomnia",
    "inspect", "inspection", "inspector",
    "instability",
    "instigate", "instigation",
    "instill",
    "instruct",
    "insubordinate", "insubordination",
    "insubstantial",
    "insufferable",
    "insufficiency", "insufficient",
    "insular",
    "insult",
    "insurance",
    "insurgent", "insurgency",
    "insurmountable",
    "insurrection",
    "intangible",
    "intense",
    "intent",
    "intentional", "intentionally",
    "intercept", "interception",
    "interfere", "interference",
    "interim",
    "interlocutory",
    "interlude",
    "intermediary",
    "interminable",
    "intermittent",
    "interrogate", "interrogation",
    "interrupt", "interruption",
    "intervene", "intervention",
    "intestate",
    "intimidate", "intimidation",
    "intolerable", "intolerance", "intolerant",
    "intoxicate",
    "intractable",
    "intransigent",
    "intricate",
    "intrude", "intruder", "intrusion", "intrusive",
    "inundate",
    "invade", "invader",
    "invalid", "invalidate", "invalidity",
    "invasion",
    "inverse",
    "investigate", "investigation", "investigator",
    "inveterate",
    "invidious",
    "invoke",
    "involuntary",
    "irrational",
    "irreconcilable",
    "irrefutable",
    "irregular", "irregularity",
    "irrelevance", "irrelevant",
    "irreparable", "irreplaceable",
    "irrepressible",
    "irresistible",
    "irresponsible",
    "irretrievable",
    "irreverent",
    "irreversible", "irrevocable",
    "irritate", "irritation",
    "isolate", "isolated", "isolation",
    "jail",
    "jam",
    "jealous", "jealousy",
    "jeopardize", "jeopardy",
    "jerk",
    "joke",
    "judgment",
    "juggle",
    "jump",
    "junk",
    "jurisdiction",
    "justification",
    "juvenile",
    "kick",
    "kidnap", "kidnapping",
    "kill", "killer", "killing",
    "knock",
    "lack",
    "lag",
    "lame", "lament", "lamentable",
    "landfill",
    "landmark",
    "lapse",
    "late",
    "latent",
    "laugh", "laughable",
    "lavish",
    "lawless", "lawsuit",
    "lay", "layoff",
    "leak", "leakage",
    "least",
    "leave",
    "ledge",
    "legacy",
    "legal",
    "lend",
    "less",
    "lessen",
    "lethal",
    "liability", "liable",
    "lie",
    "limit", "limitation", "limited",
    "liquidate", "liquidation",
    "litigant", "litigate", "litigation",
    "litter",
    "livid",
    "load",
    "loan",
    "lobby",
    "lock", "lockout",
    "lodge",
    "logistics",
    "loophole",
    "loose", "loosen",
    "loot",
    "lose", "loser", "loss", "lost",
    "loud",
    "low", "lower",
    "luck",
    "ludicrous",
    "lull",
    "lump",
    "lunatic",
    "lure",
    "lurk",
    "mad", "madden",
    "magnitude",
    "malady", "malaise",
    "malcontent",
    "malice", "malicious",
    "malign", "malignant",
    "malinger",
    "malpractice",
    "manage",
    "mandate", "mandatory",
    "maneuver",
    "manipulate", "manipulation",
    "mar",
    "margin", "marginal",
    "massacre",
    "massive",
    "master",
    "material",
    "matter",
    "meager",
    "mean",
    "meaningless",
    "measure",
    "mediocre", "mediocrity",
    "medium",
    "melancholy",
    "mellow",
    "melt", "meltdown",
    "menace",
    "merciless",
    "merge", "merger",
    "mess", "messy",
    "might",
    "migrant",
    "migrate",
    "militant",
    "mind",
    "mingle",
    "minimal",
    "minimize",
    "minor", "minority",
    "minute",
    "misappropriate", "misappropriation",
    "miscalculate", "miscalculation",
    "miscarriage",
    "mischief",
    "misconception",
    "misconduct",
    "miscreant",
    "misdeed",
    "misdemeanor",
    "misdirect",
    "miserable", "misery",
    "misfire", "misfortune",
    "misguide", "misguided",
    "mishandle", "mishap",
    "misinform", "misinformation",
    "misinterpret", "misinterpretation",
    "misjudge", "misjudgment",
    "mislabel",
    "misleading", "mismanage", "mismanagement",
    "misprint", "misquote",
    "misread", "misreport",
    "misrepresent", "misrepresentation",
    "miss", "mission",
    "misspeak",
    "misstate", "misstatement",
    "mistake", "mistaken",
    "mistreat", "mistreatment",
    "mistrial",
    "mistrust",
    "misunderstand", "misunderstanding",
    "misuse",
    "mitigate", "mitigation",
    "mix", "mixed",
    "mock", "mockery",
    "moderate",
    "modest",
    "modify",
    "molest", "molestation",
    "moment",
    "monitor",
    "monopoly",
    "monotonous",
    "monster", "monstrous",
    "mood",
    "moral", "morale",
    "moratorium",
    "morbid",
    "mortal", "mortality",
    "mortgage",
    "mortify",
    "motion",
    "mount", "mounting",
    "mourn", "mourning",
    "move",
    "mud", "muddle", "muddy",
    "murder", "murderer",
    "murky",
    "murmur",
    "mute",
    "mutiny",
    "mysterious", "mystery",
    "myth",
    "naive",
    "naked",
    "narrow", "narrowly",
    "nasty",
    "naughty",
    "nausea",
    "near",
    "necessarily",
    "necessitate",
    "need", "needless", "needy",
    "negative", "negatively",
    "neglect", "neglected",
    "negligence", "negligent", "negligible",
    "negotiate",
    "nervous",
    "nevertheless",
    "nightmare",
    "nil",
    "noise", "noisy",
    "nominal",
    "nonperformance",
    "nonsense",
    "nonetheless",
    "nonexistent",
    "normalize",
    "notable",
    "noted",
    "notice",
    "notification",
    "notorious",
    "nuclear",
    "nuisance",
    "null", "nullify",
    "obey",
    "object", "objection", "objectionable",
    "obligate", "obligated", "obligation", "obligatory",
    "oblige", "obliged",
    "obliterate",
    "oblivious",
    "obnoxious",
    "obscene", "obscenity",
    "obscure",
    "observant",
    "obsess", "obsession", "obsessive",
    "obsolete",
    "obstacle",
    "obstinate",
    "obstruct", "obstruction", "obstructive",
    "obtain",
    "obtrusive",
    "obviate",
    "obvious",
    "occupy",
    "odd", "odds",
    "offend", "offender", "offense", "offensive",
    "officer",
    "offset",
    "ominous",
    "omission", "omit",
    "onset",
    "onslaught",
    "opaque",
    "opponent",
    "opportunistic",
    "oppose", "opposed", "opposite", "opposition",
    "oppress", "oppressed", "oppression", "oppressive",
    "opt",
    "ordeal",
    "order",
    "ordinance",
    "orphan",
    "ostensibly",
    "ostracize",
    "oust",
    "outage", "outbreak", "outburst",
    "outcry", "outdated",
    "outflow",
    "outgoing",
    "outlandish",
    "outlaw",
    "outlay",
    "outlook",
    "outmoded",
    "outnumber",
    "outpace",
    "outpost",
    "outpouring",
    "outrage", "outrageous",
    "outsider",
    "outskirt",
    "outspoken",
    "outstrip",
    "outweigh",
    "overact",
    "overactive",
    "overage",
    "overall",
    "overbearing",
    "overbid",
    "overblown",
    "overbook",
    "overburden",
    "overcapacity",
    "overcharge",
    "overcome",
    "overcommit",
    "overcompensate",
    "overconfidence", "overconfident",
    "overcrowd", "overcrowded",
    "overdone",
    "overdose", "overdraft", "overdraw", "overdue",
    "overestimate",
    "overexpose", "overexposure",
    "overextend", "overextended",
    "overflow", "overhaul",
    "overheat", "overheated",
    "overissue",
    "overkill",
    "overlap",
    "overload",
    "overlook", "overlooked",
    "overly",
    "overpaid",
    "overpay", "overpayment",
    "overplay",
    "overpower",
    "overpriced",
    "overproduce", "overproduction",
    "overrate", "overrated",
    "overreach",
    "overreact", "overreaction",
    "override", "overriding",
    "overrule", "overrun",
    "oversell",
    "overshadow", "overshoot",
    "oversight",
    "oversimplify",
    "overstate", "overstatement",
    "overstay", "overstep",
    "overstock", "overstretch", "oversupply",
    "overtake", "overtax",
    "overthrow", "overtime",
    "overturn", "overuse",
    "overvalue", "overvalued",
    "overwhelm", "overwhelming",
    "overwork",
    "owe", "owing",
    "pace",
    "pack",
    "pain", "painful",
    "panic",
    "par",
    "paralysis",
    "paramount",
    "paranoid",
    "pardon",
    "parity",
    "partial",
    "partisan",
    "pass",
    "passive",
    "past",
    "patch",
    "patent",
    "pause",
    "pawn",
    "pay",
    "peculiar",
    "peddle",
    "penal", "penalize", "penalty",
    "pending",
    "penetrate",
    "pension",
    "peril", "perilous",
    "perimeter",
    "perish",
    "perjury",
    "permanent",
    "permissible",
    "permissive",
    "pernicious",
    "perpetrate", "perpetrator",
    "perpetuate",
    "perplex",
    "persecute", "persecution",
    "persist",
    "personal",
    "perspective",
    "pertain",
    "pervasive",
    "perverse", "perversion",
    "pessimism", "pessimistic",
    "pest",
    "petition", "petitioner",
    "petty",
    "phantom",
    "phase",
    "pick",
    "pile",
    "pin",
    "pirate",
    "pit", "pitch", "pitfall",
    "place",
    "plague",
    "plain",
    "plan",
    "plastic",
    "plate",
    "platform",
    "plea", "plead",
    "plead",
    "pledge",
    "plight",
    "plot", "ploy",
    "plummet", "plunge", "plunging",
    "pocket",
    "poignant",
    "point",
    "poison", "poisonous",
    "polar",
    "poll", "pollutant", "pollute", "pollution",
    "pool",
    "poor", "poorly",
    "popular",
    "portend",
    "pose",
    "position",
    "possess",
    "postpone", "postponement",
    "posture",
    "potential",
    "pound",
    "poverty",
    "powder",
    "powerless",
    "practice",
    "precarious",
    "precaution", "precautionary",
    "precede",
    "precedent",
    "precipitate", "precipitous",
    "preclude",
    "predatory",
    "predecessor",
    "predicament",
    "predict",
    "predispose",
    "preempt",
    "prejudice", "prejudicial",
    "preliminary",
    "prelude",
    "premature", "prematurely",
    "premise",
    "premium",
    "preoccupation", "preoccupy",
    "preparation",
    "prerogative",
    "prescribe", "prescription",
    "present",
    "press", "pressure",
    "presume", "presumption", "presumptuous",
    "pretax",
    "pretend", "pretense", "pretension", "pretentious",
    "prevail",
    "prevent",
    "prey",
    "price", "pricing",
    "primitive",
    "principal",
    "prior",
    "prison", "prisoner",
    "privacy",
    "private",
    "privilege", "privileged",
    "prize",
    "probable",
    "probate", "probation",
    "probe",
    "problem", "problematic",
    "proceed", "proceeding", "proceeds",
    "process",
    "proclaim",
    "procure", "procurement",
    "produce",
    "profess",
    "profit",
    "profound",
    "prohibit", "prohibited", "prohibition", "prohibitive",
    "project",
    "proliferation",
    "prolong", "prolonged",
    "promise",
    "promote",
    "prone",
    "proof",
    "propaganda",
    "propel",
    "proper",
    "property",
    "proponent",
    "proportion",
    "proposal",
    "propose",
    "proposition",
    "proprietary",
    "prosecute", "prosecution", "prosecutor",
    "prospect",
    "prosper",
    "protect",
    "protest",
    "protract", "protracted",
    "prove",
    "provide",
    "province",
    "provision", "provisional", "proviso",
    "provocation", "provocative", "provoke",
    "proxy",
    "prudence",
    "prune",
    "pseudo",
    "psychiatric",
    "psychological",
    "public",
    "pull",
    "pump",
    "punch",
    "punish", "punished", "punishment", "punitive",
    "purchase",
    "pure",
    "purge",
    "purport", "purported",
    "purpose",
    "pursuant",
    "pursue",
    "push",
    "put",
    "puzzle",
    "quake",
    "qualification",
    "qualified",
    "qualify",
    "quality",
    "qualm",
    "quarantine", "quarrel",
    "quarter",
    "quash",
    "query",
    "quest",
    "question", "questionable",
    "queue",
    "quit",
    "quota",
    "quote",
    "racism",
    "rack",
    "radical",
    "raft",
    "rage", "raid",
    "rain",
    "raise",
    "rally",
    "ramification",
    "ramp",
    "rampant",
    "random",
    "range",
    "rank",
    "ransom",
    "rap",
    "rape",
    "rapid",
    "rash",
    "rat",
    "rate",
    "ration",
    "ravage",
    "raw",
    "reach",
    "react", "reaction", "reactionary",
    "read",
    "ready",
    "real",
    "realistic",
    "reality",
    "realize",
    "reap",
    "rear",
    "reason",
    "reasonable",
    "rebel", "rebellion",
    "rebound",
    "rebuild",
    "recall",
    "recant",
    "recede",
    "receipt",
    "receive",
    "receiver", "receivership",
    "recent",
    "reception",
    "recess", "recession", "recessionary",
    "recipient",
    "reckless", "reckoning",
    "reclaim",
    "recognition",
    "recognize",
    "recollect",
    "recommend",
    "recommit",
    "reconcile", "reconciliation",
    "reconnaissance",
    "reconsider",
    "reconstitute",
    "reconstruct", "reconstruction",
    "record",
    "recount",
    "recoup",
    "recourse",
    "recover", "recovery",
    "recreation",
    "recruit",
    "rectify",
    "recur", "recurrence", "recurrent",
    "recycle",
    "redeem", "redeemable", "redemption",
    "redesign",
    "redirect",
    "redistribute", "redistribution",
    "redress",
    "reduce", "reduced", "reduction",
    "redundancy", "redundant",
    "refer", "referee", "reference", "referendum", "referral",
    "refine",
    "reflect",
    "reform",
    "refrain",
    "refresh",
    "refuge", "refugee",
    "refund", "refundable",
    "refurbish",
    "refusal", "refuse", "refused",
    "refute",
    "regain",
    "regard",
    "regardless",
    "regime",
    "region",
    "register", "registered", "registrant", "registration",
    "regress", "regression",
    "regret", "regretful", "regrettable",
    "regroup",
    "regular",
    "regulate", "regulated", "regulation", "regulator", "regulatory",
    "rehabilitate", "rehabilitation",
    "rehearing",
    "reign",
    "reimburse", "reimbursement",
    "rein", "reinforce",
    "reinstate", "reinstatement",
    "reinsurance",
    "reiterate",
    "reject", "rejected", "rejection",
    "rejoice",
    "relate", "related", "relation", "relationship",
    "relative",
    "relax", "relaxation",
    "release",
    "relegate",
    "relentless",
    "relevance", "relevant",
    "reliability", "reliable",
    "reliance", "reliant",
    "relief", "relieve",
    "religion", "religious",
    "relinquish",
    "relocate", "relocation",
    "reluctance", "reluctant",
    "remain", "remainder", "remains",
    "remark", "remarkable",
    "remedial", "remedy",
    "remember",
    "remind",
    "reminder",
    "reminiscent",
    "remission", "remit", "remittance",
    "remnant",
    "remodel",
    "remote",
    "removal", "remove", "removed",
    "remunerate", "remuneration",
    "render",
    "renegotiate",
    "renew", "renewable", "renewal", "renewed",
    "renounce",
    "renovate", "renovation",
    "rent", "rental",
    "reopen",
    "reorganization", "reorganize",
    "repair",
    "repatriate", "repatriation",
    "repay", "repayable", "repayment",
    "repeal",
    "repeat", "repeatedly",
    "repel",
    "repercussion",
    "repetitive",
    "replace", "replacement",
    "replenish", "replenishment",
    "replete",
    "replicate",
    "reply",
    "report", "reported", "reporter", "reporting",
    "represent", "representation", "representative",
    "repress", "repression",
    "reprieve",
    "reprimand",
    "reprisal",
    "reproach",
    "reproduce", "reproduction",
    "repudiate", "repudiation",
    "repugnant",
    "repulse", "repulsive",
    "reputable", "reputation",
    "request", "requested",
    "require", "required", "requirement", "requisite",
    "rescind",
    "rescue", "research",
    "resemblance", "resemble",
    "resent", "resentful", "resentment",
    "reservation",
    "reserve", "reserved", "reserves",
    "reservoir",
    "reset",
    "resettle", "resettlement",
    "reside", "residence", "resident", "residential",
    "residual",
    "resign", "resignation", "resigned",
    "resilience", "resilient",
    "resist", "resistance", "resistant",
    "resolution", "resolve", "resolved",
    "resonate",
    "resort",
    "resource",
    "respect", "respected",
    "respective",
    "respond", "respondent", "response", "responsibility", "responsible",
    "responsive",
    "rest", "restart",
    "restoration", "restore", "restored",
    "restrain", "restraint",
    "restrict", "restricted", "restriction", "restrictive",
    "restructure", "restructured", "restructuring",
    "result",
    "resume", "resumption",
    "retain", "retained", "retention",
    "retaliate", "retaliation",
    "retire", "retired", "retirement",
    "retool",
    "retract",
    "retreat",
    "retrench", "retrenchment",
    "retrieve",
    "return", "returned", "returns",
    "reveal", "revealed",
    "revenge",
    "revenue",
    "reverse", "reversible",
    "revert",
    "review", "reviewed",
    "revise", "revised", "revision",
    "revitalize",
    "revival", "revive",
    "revoke",
    "revolt", "revolution",
    "reward",
    "rework",
    "rid",
    "riddle",
    "ride",
    "rift",
    "right",
    "rigid",
    "rigor", "rigorous",
    "riot",
    "rip",
    "ripe",
    "rise",
    "risk", "risky",
    "rival",
    "rivalry",
    "rock",
    "rogue",
    "roll",
    "root",
    "rotate",
    "rough", "roughly",
    "round",
    "rouse",
    "rout",
    "route",
    "routine",
    "row",
    "royalty",
    "rub",
    "rude",
    "ruin", "ruined", "ruinous",
    "rule",
    "ruling",
    "run",
    "running",
    "rupture",
    "rural",
    "rush",
    "rust",
    "sabotage",
    "sacrifice",
    "sad",
    "saddle",
    "safe",
    "safeguard",
    "safety",
    "sag",
    "saga",
    "sake",
    "salary",
    "sale",
    "salient",
    "salvage",
    "same",
    "sample",
    "sanction", "sanctioned",
    "sap",
    "satisfaction",
    "satisfy",
    "saturate", "saturated", "saturation",
    "save",
    "saving",
    "scale",
    "scandal",
    "scanty",
    "scar", "scarce", "scarcely", "scarcity",
    "scare",
    "scatter",
    "scenario",
    "schedule",
    "scheme",
    "scope",
    "score",
    "scrap",
    "screen",
    "screw",
    "scrutiny",
    "seal",
    "search",
    "season",
    "seat",
    "secede",
    "secession",
    "second",
    "secondary",
    "secrecy", "secret",
    "section",
    "sector",
    "secure", "secured",
    "security",
    "sedition",
    "seed",
    "seek",
    "segment",
    "seize",
    "seizure",
    "select",
    "self",
    "sell",
    "seller",
    "senior",
    "sense",
    "sensitive", "sensitivity",
    "sentence",
    "sentiment",
    "separate", "separation",
    "sequel",
    "sequence",
    "series",
    "serious", "seriously",
    "serve",
    "service",
    "session",
    "set",
    "settle", "settled", "settlement",
    "setup",
    "severe", "severely", "severity",
    "shackle",
    "shadow",
    "shaft",
    "shake", "shakeout",
    "shaky",
    "shallow",
    "sham",
    "shambles",
    "shame",
    "shape",
    "share",
    "sharp", "sharply",
    "shatter", "shattered",
    "shed",
    "sheet",
    "shelf",
    "shell",
    "shelter",
    "shield",
    "shift",
    "shine",
    "ship",
    "shock", "shocking",
    "shoot",
    "shore",
    "short", "shortage", "shortfall",
    "shortsighted",
    "shot",
    "shoulder",
    "show",
    "shower",
    "shred",
    "shrink", "shrinkage",
    "shroud",
    "shrug",
    "shun",
    "shutdown",
    "shutout",
    "shy",
    "sick",
    "side",
    "sidetrack",
    "siege",
    "sight",
    "sign",
    "signal",
    "signatory",
    "signature",
    "significance",
    "significant",
    "signify",
    "silence",
    "silent",
    "silly",
    "silt",
    "similar",
    "simple",
    "simplify",
    "simply",
    "simulate",
    "simultaneous",
    "sin",
    "since",
    "sincere",
    "single",
    "singular",
    "sink",
    "sinking",
    "sip",
    "sit",
    "site",
    "situation",
    "size",
    "skeptic",
    "skeptical",
    "sketch",
    "skid",
    "skill",
    "skim",
    "skin",
    "skip",
    "skirmish",
    "skyrocket",
    "slack",
    "slam",
    "slash",
    "slate",
    "slaughter",
    "slave",
    "sleep",
    "slice",
    "slide",
    "slight", "slightly",
    "slip", "slippage",
    "slit",
    "slogan",
    "slope",
    "slot",
    "slow", "slowdown", "slowly",
    "slump",
    "small",
    "smart",
    "smash",
    "smell",
    "smile",
    "smoke",
    "smooth",
    "smuggle",
    "snap",
    "snarl",
    "sneak",
    "snowball",
    "soak",
    "soar",
    "social",
    "society",
    "soft", "soften",
    "software",
    "soil",
    "sole",
    "solicit",
    "solid",
    "solution",
    "solve",
    "somewhat",
    "soothe",
    "sordid",
    "sort",
    "sound",
    "source",
    "sovereign",
    "space",
    "span",
    "spare",
    "spark",
    "speak",
    "special",
    "specialist",
    "species",
    "specific", "specifically",
    "specification", "specify",
    "specimen",
    "speculate", "speculation", "speculative",
    "speech",
    "speed",
    "spend", "spending",
    "spin",
    "spirit",
    "split",
    "spoil",
    "sponsor",
    "spot",
    "spread",
    "spring",
    "spur",
    "spy",
    "squabble",
    "squander",
    "square",
    "squeeze",
    "stab",
    "stability",
    "stabilize",
    "stable",
    "stack",
    "staff",
    "stage",
    "stagnant", "stagnate", "stagnation",
    "stake",
    "stale",
    "stall",
    "stamp",
    "stance",
    "stand", "standard",
    "standing",
    "standoff",
    "standpoint",
    "stark",
    "start",
    "startle",
    "starvation", "starve",
    "state",
    "statement",
    "station",
    "statistical",
    "status",
    "statute", "statutory",
    "stay",
    "steady",
    "steal",
    "steam",
    "steep",
    "stem",
    "step",
    "sterling",
    "stern",
    "steward",
    "stick", "sticky",
    "stiff", "stiffen",
    "stifle",
    "stigma",
    "still",
    "stimulate", "stimulus",
    "stipulate", "stipulation",
    "stir",
    "stitch",
    "stock",
    "stockpile",
    "stole",
    "stop",
    "storage",
    "store",
    "storm",
    "story",
    "straight",
    "straighten",
    "straightforward",
    "strain",
    "strand", "stranded",
    "strange",
    "strangle",
    "strategic",
    "strategy",
    "stream",
    "streamline",
    "street",
    "strength",
    "strengthen",
    "stress",
    "stretch",
    "strict", "strictly",
    "stride",
    "strife",
    "strike", "striking",
    "string", "stringent",
    "strip",
    "strive",
    "stroke",
    "strong", "strongly",
    "struggle",
    "stubborn",
    "stud",
    "student",
    "studied",
    "study",
    "stuff",
    "stumble",
    "stun",
    "stunt",
    "stupid",
    "sturdy",
    "style",
    "subdue", "subdued",
    "subject",
    "submission", "submit", "submitted",
    "subordinate",
    "subsequent",
    "subsidiary",
    "subsidize", "subsidy",
    "substance",
    "substantial", "substantially",
    "substantiate", "substantive",
    "substitute", "substitution",
    "subtle",
    "subtract",
    "subvert", "subversion",
    "succeed", "success",
    "successful",
    "succession", "successive", "successor",
    "succinct",
    "succumb",
    "sue",
    "suffer", "suffering",
    "sufficient",
    "suggest", "suggestion",
    "suit", "suitable",
    "suite",
    "sum",
    "summarize",
    "summary",
    "summit",
    "summon",
    "sunk",
    "sunset",
    "super",
    "superb",
    "superficial",
    "superfluous",
    "superior",
    "supervision",
    "supervisor",
    "supplant",
    "supplement",
    "supplier",
    "supply",
    "support",
    "suppose",
    "supposed",
    "suppress", "suppression",
    "supreme",
    "surcharge",
    "sure",
    "surface",
    "surge",
    "surplus",
    "surprise", "surprised", "surprising",
    "surrender",
    "surround",
    "surveillance",
    "survey",
    "survival", "survive", "survivor",
    "susceptible",
    "suspect",
    "suspend", "suspense", "suspension",
    "suspicion", "suspicious",
    "sustain", "sustainable", "sustained",
    "swap",
    "sway",
    "sweep",
    "sweeping",
    "sweet",
    "swell",
    "swerve",
    "swift",
    "swing",
    "switch",
    "swoon",
    "sword",
    "symbolic",
    "sympathetic", "sympathy",
    "symptom",
    "syndicate",
    "syndrome",
    "synergy",
    "system",
    "systematic",
    "table",
    "tackle",
    "tactical",
    "tail",
    "tailor",
    "take",
    "takeover",
    "tale",
    "talent",
    "talk",
    "tally",
    "tamper",
    "tangible",
    "tangle",
    "tap",
    "tape",
    "target",
    "tariff",
    "task",
    "taste",
    "taut",
    "tax",
    "teach",
    "team",
    "tear",
    "tease",
    "technical",
    "technique",
    "technology",
    "tedious",
    "teeter",
    "telephone",
    "television",
    "tell",
    "temper",
    "temporary",
    "tempt", "temptation",
    "tenacious",
    "tenant",
    "tend",
    "tendency",
    "tender",
    "tense", "tension",
    "tentative",
    "tenuous",
    "tenure",
    "term",
    "terminal",
    "terminate", "termination",
    "terms",
    "terrain",
    "terrible", "terrific",
    "territory",
    "terror", "terrorism", "terrorist",
    "test",
    "testament",
    "testify", "testimony",
    "testing",
    "thank",
    "theft",
    "theme",
    "theoretical",
    "theory",
    "therapy",
    "thereby",
    "thereof",
    "thick",
    "thin",
    "thing",
    "think",
    "thinking",
    "thirst",
    "thorn",
    "thorough",
    "thought",
    "thoughtful",
    "thrash",
    "thread",
    "threat", "threaten",
    "threshold",
    "thrift",
    "thrive",
    "throat",
    "throttle",
    "through",
    "throughout",
    "throw",
    "thrust",
    "thumb",
    "ticket",
    "tide",
    "tie",
    "tight", "tighten",
    "tilt",
    "time",
    "timely",
    "timing",
    "tip",
    "tire",
    "tissue",
    "title",
    "today",
    "toddle",
    "together",
    "toil",
    "token",
    "tolerable", "tolerance", "tolerant", "tolerate",
    "toll",
    "tomorrow",
    "tone",
    "tool",
    "tooth",
    "top",
    "topic",
    "torch",
    "torment",
    "torn",
    "torture",
    "toss",
    "total",
    "touch",
    "tough",
    "tour",
    "toward",
    "town",
    "toxic", "toxin",
    "trace",
    "track",
    "tract",
    "trade",
    "trader",
    "trading",
    "tradition",
    "traditional",
    "traffic",
    "tragedy", "tragic",
    "trail",
    "train",
    "trait",
    "trample",
    "tranquil",
    "transaction",
    "transcend",
    "transcript",
    "transfer",
    "transform",
    "transformation",
    "transgress", "transgression",
    "transient",
    "transition",
    "transparency", "transparent",
    "transport",
    "trap",
    "trauma", "traumatic",
    "travel",
    "treachery",
    "treason",
    "treasure",
    "treat",
    "treatment",
    "treaty",
    "tremble",
    "tremendous",
    "trend",
    "trespass",
    "trial",
    "tribunal",
    "tribute",
    "trick",
    "trigger",
    "trim",
    "triumph",
    "trivial",
    "troop",
    "trouble", "troubled", "troublesome",
    "truce",
    "true",
    "truly",
    "trump",
    "trunk",
    "trust", "trusted",
    "trustee",
    "truth",
    "try",
    "tug",
    "tumble",
    "tune",
    "tunnel",
    "turmoil",
    "turn",
    "turnover",
    "tussle",
    "tutor",
    "twist",
    "twofold",
    "type",
    "typical",
    "ugly",
    "ultimate",
    "ultimatum",
    "unable",
    "unacceptable",
    "unaccountable",
    "unaccustomed",
    "unachievable",
    "unaddressed",
    "unadjusted",
    "unadorned",
    "unadulterated",
    "unaffected",
    "unaffordable",
    "unaided",
    "unallocated",
    "unallowable",
    "unambiguous",
    "unanimous",
    "unanswered",
    "unanticipated",
    "unappealing",
    "unappreciated",
    "unapproachable",
    "unapproved",
    "unassailable",
    "unassertive",
    "unassigned",
    "unattached",
    "unattainable",
    "unattended",
    "unattractive",
    "unaudited",
    "unauthorized",
    "unavailable",
    "unavoidable",
    "unaware",
    "unbalance", "unbalanced",
    "unbearable",
    "unbecoming",
    "unbelief",
    "unbelievable",
    "unbiased",
    "unbroken",
    "uncertain", "uncertainty",
    "unchanged",
    "uncharacteristic",
    "uncharted",
    "unchecked",
    "unclaimed",
    "unclassified",
    "uncle",
    "unclear",
    "uncollectible",
    "uncomfortable",
    "uncommitted",
    "uncommon",
    "uncompetitive",
    "uncomplimentary",
    "uncompromising",
    "unconcealed",
    "unconcerned",
    "unconditional",
    "unconfirmed",
    "unconnected",
    "unconscionable",
    "unconscious",
    "unconstitutional",
    "unconstrained",
    "uncontested",
    "uncontrollable", "uncontrolled",
    "unconventional",
    "unconvincing",
    "uncooperative",
    "uncoordinated",
    "uncorrected",
    "uncorroborated",
    "uncover",
    "uncritical",
    "undamaged",
    "undated",
    "undaunted",
    "undecided",
    "undefined",
    "undelivered",
    "undemocratic",
    "undercapitalized",
    "undercut",
    "underdeveloped",
    "underdog",
    "underemployment",
    "underestimate", "underestimation",
    "undergo",
    "underinvestment",
    "underlying",
    "undermine", "undermined",
    "underpaid",
    "underperform", "underperformance",
    "underpowered",
    "underprice",
    "underreport",
    "underrepresented",
    "underscore",
    "undersigned",
    "understand",
    "understanding",
    "understate", "understatement",
    "underway",
    "underwrite",
    "undesirable", "undesired",
    "undetected",
    "undetermined",
    "undisclosed",
    "undiscovered",
    "undisputed",
    "undistributed",
    "undisturbed",
    "undivided",
    "undo",
    "undocumented",
    "undone",
    "undoubted", "undoubtedly",
    "undue",
    "unduly",
    "uneamed",
    "unearthed",
    "unease", "uneasy",
    "uneconomic", "uneconomical",
    "unemployed", "unemployment",
    "unencumbered",
    "unending",
    "unenforceable",
    "unenlightened",
    "unenterprising",
    "unenviable",
    "unequal",
    "unequaled",
    "unequivocal", "unequivocally",
    "unerring",
    "unessential",
    "unethical",
    "uneven",
    "uneventful",
    "unexamined",
    "unexceptionable",
    "unexpected", "unexpectedly",
    "unexplained",
    "unexplored",
    "unexpressive",
    "unfailing",
    "unfair", "unfairly", "unfairness",
    "unfaithful",
    "unfamiliar",
    "unfashionable",
    "unfavorable",
    "unfeasible",
    "unfilled",
    "unfinished",
    "unfit",
    "unforeseeable", "unforeseen",
    "unforgettable",
    "unfortunate", "unfortunately",
    "unfounded",
    "unfriendly",
    "unfulfilled",
    "unfunded",
    "unguarded",
    "unhappiness", "unhappy",
    "unharmed",
    "unhealthy",
    "unheralded",
    "unidentified",
    "unification",
    "unified",
    "uniform",
    "unilateral",
    "unimaginable",
    "unimpaired",
    "unimpeachable",
    "unimplemented",
    "unimportant",
    "unimproved",
    "unincorporated",
    "uninformed",
    "uninhabitable",
    "uninhibited",
    "uninitiated",
    "uninjured",
    "uninspired",
    "uninsurable",
    "uninsured",
    "unintelligent",
    "unintelligible",
    "unintended", "unintentional",
    "uninterested",
    "uninterrupted",
    "uninvested",
    "uninvited",
    "union",
    "unique",
    "united",
    "unity",
    "universal",
    "unjust", "unjustifiable", "unjustified", "unjustly",
    "unkind",
    "unknown",
    "unlawful", "unlawfully",
    "unleaded",
    "unleash",
    "unless",
    "unlikely",
    "unlimited",
    "unliquidated",
    "unlisted",
    "unload",
    "unlock",
    "unloved",
    "unmanageable",
    "unmanned",
    "unmarked",
    "unmarried",
    "unmatched",
    "unmemorable",
    "unmistakable",
    "unmitigated",
    "unmodified",
    "unmonitored",
    "unnatural",
    "unnecessary", "unnecessarily",
    "unnoticed",
    "unobserved",
    "unobtainable",
    "unoccupied",
    "unofficial",
    "unopened",
    "unopposed",
    "unorganized",
    "unorthodox",
    "unpaid",
    "unparalleled",
    "unpardonable",
    "unpatriotic",
    "unplanned",
    "unpleasant",
    "unpopular",
    "unprecedented",
    "unpredictable", "unpredictability",
    "unprejudiced",
    "unprepared",
    "unproductive",
    "unprofessional",
    "unprofitable",
    "unpromising",
    "unprotected",
    "unproven",
    "unpublished",
    "unqualified",
    "unquestionable", "unquestioned",
    "unquote",
    "unravel",
    "unreachable",
    "unrealistic", "unrealized",
    "unreasonable", "unreasonably",
    "unrecognized",
    "unrecorded",
    "unrefined",
    "unregulated",
    "unrelated",
    "unreleased",
    "unrelenting",
    "unreliable",
    "unrelieved",
    "unremarkable",
    "unremedied",
    "unreported",
    "unrepresentative",
    "unrequited",
    "unreserved",
    "unresolved",
    "unresponsive",
    "unrest",
    "unrestricted",
    "unrewarding",
    "unrivaled",
    "unruffled",
    "unsafe",
    "unsaid",
    "unsalable",
    "unsatisfactory", "unsatisfied",
    "unsaturated",
    "unscheduled",
    "unscientific",
    "unscrupulous",
    "unseemly",
    "unseen",
    "unselfish",
    "unsettle", "unsettled",
    "unshakable",
    "unskilled",
    "unsociable",
    "unsold",
    "unsolicited",
    "unsolved",
    "unsophisticated",
    "unsound",
    "unspecified",
    "unspent",
    "unstable",
    "unstated",
    "unsteady",
    "unstop",
    "unsubstantiated",
    "unsuccessful", "unsuccessfully",
    "unsuitable",
    "unsuited",
    "unsupported",
    "unsure",
    "unsuspecting",
    "unsustainable",
    "untapped",
    "untenable",
    "untested",
    "unthinkable",
    "untidy",
    "untimely",
    "untouched",
    "untrained",
    "untreated",
    "untried",
    "untrue",
    "untrustworthy",
    "untruth",
    "unturned",
    "unused",
    "unusual", "unusually",
    "unutterable",
    "unverified",
    "unwanted",
    "unwarranted",
    "unwelcome",
    "unwell",
    "unwilling", "unwillingness",
    "unwind",
    "unwise",
    "unwitting",
    "unworkable",
    "unworthy",
    "unwrap",
    "unwritten",
    "unyielding",
    "upbraid",
    "update",
    "upfront",
    "upgrade",
    "upheaval",
    "uphold",
    "upkeep",
    "uplift",
    "upper",
    "upright",
    "uprising",
    "uproar",
    "uproot",
    "upset", "upsetting",
    "upshot",
    "upside",
    "upstage",
    "upstart",
    "upstream",
    "uptick",
    "upturn",
    "upward",
    "urban",
    "urge", "urgency", "urgent",
    "usable",
    "usage",
    "useful",
    "useless",
    "user",
    "usual",
    "usurp",
    "utilitarian",
    "utility",
    "utilize",
    "utmost",
    "utter", "utterly",
    "vacancy", "vacant",
    "vacate",
    "vacuum",
    "vague", "vaguely",
    "vain",
    "valid",
    "validate",
    "validity",
    "valuable", "valuation", "value",
    "vanish",
    "vanity",
    "vapid",
    "variability",
    "variable",
    "variance",
    "variant",
    "variation",
    "varied",
    "variety",
    "various",
    "vary",
    "vast",
    "vault",
    "veer",
    "vegetate",
    "vehement",
    "vehicle",
    "velocity",
    "vendetta",
    "vendor",
    "veneer",
    "vengeance",
    "venom",
    "venture",
    "venue",
    "verbal",
    "verdict",
    "verge",
    "verify",
    "veritable",
    "versatile",
    "verse",
    "version",
    "versus",
    "vertical",
    "vest",
    "vested",
    "veto",
    "vex",
    "viability", "viable",
    "vibrant",
    "vice",
    "vicinity",
    "vicious",
    "victim", "victimize",
    "victory",
    "video",
    "view",
    "vigilance", "vigilant",
    "vigor", "vigorous",
    "vile",
    "vindicate",
    "violate", "violation", "violence", "violent",
    "virtually",
    "virtue",
    "virus",
    "visa",
    "visible",
    "vision",
    "visit",
    "visitor",
    "visual",
    "vital",
    "vitality",
    "vitamin",
    "vivid",
    "vocal",
    "vocation",
    "voice",
    "void",
    "volatile", "volatility",
    "volume",
    "voluntary",
    "volunteer",
    "vomit",
    "vote",
    "vouch",
    "vow",
    "voyage",
    "vulgar",
    "vulnerability", "vulnerable",
    "wade",
    "wage",
    "wait",
    "waive", "waiver",
    "wake",
    "walk",
    "wall",
    "wander",
    "want",
    "war",
    "ward",
    "warehouse",
    "warfare",
    "warm",
    "warn", "warning",
    "warrant",
    "warranty",
    "warrior",
    "wary",
    "wash",
    "waste", "wasteful",
    "watch",
    "water",
    "wave",
    "waver",
    "wax",
    "way",
    "weak", "weaken", "weakening", "weakness",
    "wealth",
    "wealthy",
    "weapon",
    "wear",
    "weather",
    "weave",
    "web",
    "wedding",
    "weed",
    "week",
    "weekly",
    "weigh",
    "weight",
    "weird",
    "welcome",
    "welfare",
    "well",
    "wellness",
    "west",
    "wet",
    "whim",
    "whip",
    "whirl",
    "whisper",
    "white",
    "whole",
    "wholesale",
    "wholesome",
    "widespread",
    "width",
    "wield",
    "wife",
    "wild",
    "will",
    "willing", "willingness",
    "win",
    "wind",
    "window",
    "wine",
    "wing",
    "winner",
    "winning",
    "wipe",
    "wire",
    "wisdom",
    "wise",
    "wish",
    "wit",
    "withdraw", "withdrawal", "withdrawn",
    "wither",
    "withhold", "withholding",
    "within",
    "without",
    "withstand",
    "witness",
    "wonder",
    "wonderful",
    "word",
    "work",
    "workable",
    "worker",
    "workforce",
    "working",
    "workload",
    "works",
    "workshop",
    "world",
    "worldwide",
    "worry", "worrying",
    "worse", "worsen", "worsening", "worship",
    "worst",
    "worth", "worthless", "worthwhile", "worthy",
    "wound", "wounded",
    "wrap",
    "wreck", "wreckage",
    "wrestle",
    "wretched",
    "wring",
    "wrinkle",
    "write",
    "writer",
    "written",
    "wrong", "wrongdoing",
    "wrought",
    "yard",
    "year",
    "yearly",
    "yell",
    "yellow",
    "yield",
    "young",
    "youth",
    "zeal",
    "zero",
    "zone",
})

UNCERTAINTY_WORDS: frozenset[str] = frozenset({
    "abeyance", "ambiguous", "ambiguity", "ambivalent",
    "apprehensive", "approximate", "approximated", "approximation",
    "arbitrary", "assume", "assumed", "assumption",
    "believe", "believed",
    "blur", "blurred",
    "can", "cannot", "could",
    "conceivable", "conceivably",
    "conjecture", "contingency", "contingent",
    "could", "depend", "depends",
    "doubt", "doubtful",
    "epidemic",
    "estimate", "estimated", "estimation",
    "evolve", "evolved", "evolution",
    "expect", "expectation", "expected",
    "fear", "fears",
    "feel", "feeling",
    "fluctuate", "fluctuated", "fluctuation",
    "forecast", "forecasts",
    "fudge",
    "guess",
    "hazy",
    "hope",
    "hypothetical", "hypothetically",
    "if",
    "imprecise",
    "inconclusive",
    "indefinite", "indefinitely",
    "indeterminate",
    "inexact",
    "innovate", "innovation", "innovative",
    "insolvency", "insolvent",
    "instability", "instable",
    "intangible",
    "likely",
    "loose",
    "may", "maybe", "might",
    "milestone",
    "murky",
    "nearly",
    "negotiate", "negotiation",
    "obscure",
    "optimistic",
    "option", "optional",
    "pandemic",
    "pending",
    "perhaps",
    "plausible",
    "possibility", "possible", "possibly", "potential", "potentially",
    "precaution", "precautionary",
    "predict", "predictable", "prediction", "predictions",
    "preliminary",
    "presume", "presumably", "presumption",
    "probable", "probably", "probability",
    "prognosis", "prognosticate",
    "project", "projected", "projection", "projections",
    "provisional",
    "reckon",
    "rely", "reliance",
    "reorganize", "reorganization",
    "reshuffle",
    "resolve", "resolved",
    "restructure", "restructuring",
    "rough", "roughly",
    "rumor", "rumored",
    "scenario", "scenarios",
    "seem", "seems", "seemed",
    "shall",
    "should",
    "somewhat",
    "speculate", "speculation", "speculative",
    "suppose", "supposedly",
    "suspect",
    "tentative", "tentatively",
    "tenuous",
    "think",
    "turbulence", "turbulent",
    "uncertain", "uncertainty", "uncertainties",
    "unclear",
    "unconfirmed",
    "unconventional",
    "undecided",
    "underestimate",
    "unexplained",
    "unfamiliar",
    "unforeseeable", "unforeseen",
    "unpredictable", "unpredictability",
    "unproven",
    "unsettled",
    "unspecified",
    "unstable",
    "unsubstantiated",
    "unsure",
    "vague", "vaguely",
    "variability", "variable", "variance",
    "volatile", "volatility",
    "wait", "waiting",
    "what", "whatever",
    "when", "whenever",
    "where", "whereas",
    "whether",
    "whim",
    "will",
    "would",
})

LITIGIOUS_WORDS: frozenset[str] = frozenset({
    "abatement", "abeyance", "abrogate", "abscond",
    "accusation", "accuse", "accused",
    "acquit", "acquittal",
    "adjudicate", "adjudication", "adjudicator",
    "administrator",
    "admissible", "admission", "admit",
    "admonish", "admonition",
    "adversary", "adverse", "adversely",
    "advocate",
    "affiant", "affidavit",
    "allegation", "allege", "alleged", "allegedly",
    "amend", "amended", "amendment",
    "annul", "annulment",
    "answer",
    "antitrust",
    "apparatus",
    "appeal", "appealed", "appellant", "appellate",
    "appear", "appearance",
    "appointee",
    "arbitrary",
    "arbitrate", "arbitration", "arbitrator",
    "arraign", "arraignment",
    "arrest",
    "assault",
    "assess", "assessment",
    "attorney",
    "audit", "auditor",
    "authority", "authorization", "authorize",
    "bail",
    "bankrupt", "bankruptcy",
    "bar",
    "battery",
    "benchmark",
    "bequest",
    "bid", "bidder",
    "bill",
    "bind", "binding",
    "board",
    "bond",
    "borrower",
    "breach",
    "bribe", "bribery",
    "brief",
    "broker",
    "burden",
    "burglary",
    "bypass",
    "canon",
    "capacity",
    "capital",
    "caveat",
    "cease",
    "certificate", "certification", "certified", "certify",
    "challenge",
    "chamber",
    "chancellor",
    "charge",
    "charter",
    "circuit",
    "circumstantial",
    "citation", "cite", "cited",
    "civil",
    "claim", "claimant", "claims",
    "class",
    "classification", "classified",
    "clause",
    "clear", "clearance",
    "clerk",
    "client",
    "close", "closing",
    "code",
    "codicil",
    "coerce", "coercion", "coercive",
    "collateral",
    "collect", "collection",
    "commence", "commencement",
    "commission", "commissioner",
    "commit", "commitment",
    "committee",
    "common",
    "compel", "compelling",
    "compensate", "compensation", "compensatory",
    "competent",
    "complain", "complainant", "complaint",
    "compliance", "compliant",
    "condition", "conditional",
    "conduct",
    "confer",
    "confess", "confession",
    "confidential", "confidentiality",
    "confiscate", "confiscation",
    "conflict",
    "consent",
    "consequence", "consequent", "consequential",
    "conservator",
    "consideration",
    "consign", "consignment",
    "consolidate", "consolidated", "consolidation",
    "conspiracy", "conspire",
    "constitute", "constitution", "constitutional",
    "constrain", "constraint",
    "construction",
    "construe",
    "consult", "consultant", "consultation",
    "contempt",
    "contend",
    "contest", "contestable",
    "contingency", "contingent",
    "continuance",
    "contract", "contractor", "contractual",
    "contradict",
    "contribute", "contribution",
    "controversy", "controversial",
    "convene",
    "convention",
    "convict", "conviction",
    "copyright",
    "corporate",
    "corpus",
    "correct", "correction", "corrective",
    "corroborate",
    "counsel", "counseling", "counselor",
    "counterclaim",
    "counterfeit",
    "court",
    "covenant",
    "creditor",
    "crime", "criminal",
    "cross-claim",
    "cross-examination", "cross-examine",
    "custodian", "custody",
    "damage", "damages",
    "de facto",
    "de novo",
    "debt", "debtor",
    "deceit", "deceitful",
    "decide", "decision", "decisional",
    "declaration", "declare", "declared",
    "decree",
    "deed",
    "defalcation",
    "defamation", "defamatory",
    "default", "defaulted",
    "defeat",
    "defect", "defective",
    "defend", "defendant", "defender", "defense",
    "defer", "deference", "deferral", "deferred",
    "deficiency",
    "define",
    "defraud",
    "degree",
    "delay",
    "delegate", "delegation",
    "deliberate", "deliberation",
    "delinquency", "delinquent",
    "deliver", "delivery",
    "demand",
    "demur", "demurrer",
    "denial", "deny",
    "department",
    "departure",
    "depend", "dependence", "dependent",
    "deponent",
    "deport", "deportation",
    "depose", "deposition",
    "deposit",
    "depreciate", "depreciation",
    "derivative",
    "detain", "detention",
    "deter", "deterrent",
    "determination", "determine",
    "devise",
    "dictate",
    "diligence",
    "direct", "direction", "directive", "director",
    "disbar", "disbarment",
    "discharge",
    "disclaim", "disclaimer",
    "disclose", "disclosed", "disclosure",
    "discontinuance",
    "discover", "discovery",
    "discretion", "discretionary",
    "discriminate", "discrimination", "discriminatory",
    "dismiss", "dismissal",
    "disorderly",
    "disparate", "disparity",
    "disposition",
    "dispute",
    "disqualification", "disqualify",
    "dissolution", "dissolve",
    "distribute", "distribution",
    "district",
    "docket",
    "document", "documentation",
    "domicile",
    "donor",
    "due",
    "duly",
    "duress",
    "duty",
    "easement",
    "effect",
    "eject", "ejectment",
    "election",
    "emancipate",
    "embargo",
    "embezzle", "embezzlement",
    "enact", "enactment",
    "enforce", "enforceable", "enforcement",
    "enjoin",
    "entitle", "entitled", "entitlement",
    "entity",
    "entrapment",
    "entry",
    "equal", "equality",
    "equitable",
    "equity",
    "err", "error",
    "escalate", "escalation",
    "escheat",
    "escrow",
    "establish", "establishment",
    "estate",
    "estop", "estoppel",
    "evaluate", "evaluation",
    "evict", "eviction",
    "evidence",
    "ex parte",
    "examination", "examine", "examiner",
    "exception",
    "excess",
    "exchange",
    "excise",
    "exclusion", "exclusive",
    "execute", "executed", "execution", "executive", "executor",
    "exemplary",
    "exempt", "exemption",
    "exhibit",
    "exonerate",
    "expert",
    "expiration", "expire",
    "exploit",
    "expropriate", "expropriation",
    "expunge",
    "expulsion",
    "extend", "extension",
    "extortion", "extortionate",
    "extradition",
    "fact", "factor",
    "fair", "fairly", "fairness",
    "false", "falsehood", "falsify",
    "fault",
    "federal",
    "fee",
    "felony", "felonious",
    "fictitious",
    "fidelity",
    "fiduciary",
    "file", "filed", "filing",
    "final", "finalize",
    "finance", "financial",
    "finding",
    "fine",
    "firm",
    "fixture",
    "forbearance",
    "foreclose", "foreclosure",
    "foreign",
    "forfeit", "forfeiture",
    "forged", "forgery",
    "form",
    "forum",
    "foster",
    "foundation",
    "founder",
    "franchise",
    "fraud", "fraudulent",
    "free",
    "freeze",
    "fugitive",
    "fund",
    "garnishment",
    "gift",
    "good faith",
    "goods",
    "govern", "governance", "government", "governmental",
    "grant", "granted", "grantee", "grantor",
    "gratuitous",
    "guarantee", "guaranty",
    "guardian", "guardianship",
    "guilt", "guilty",
    "habeas corpus",
    "hearing",
    "hearsay",
    "heir",
    "holder",
    "hold harmless",
    "honor",
    "illegal", "illegality",
    "illegitimate",
    "illicit",
    "immaterial",
    "immigrant",
    "immunity",
    "impair", "impaired", "impairment",
    "impanel",
    "impeach", "impeachment",
    "impede",
    "implement", "implementation",
    "implicate", "implication",
    "impose", "imposed", "imposition",
    "impound",
    "imprison", "imprisonment",
    "improper", "improperly",
    "in lieu of",
    "in re",
    "inadmissible",
    "inalienable",
    "incapacitate", "incapacity",
    "incarcerate", "incarceration",
    "inception",
    "incite",
    "incoming",
    "incorporate",
    "incriminate",
    "incur", "incurred",
    "indebted", "indebtedness",
    "indemnification", "indemnify", "indemnity",
    "indenture",
    "independent",
    "indicate",
    "indict", "indictable", "indictment",
    "indorse", "indorsement",
    "induce",
    "inference",
    "informant",
    "information",
    "infraction",
    "infringe", "infringement",
    "inherent",
    "inheritance",
    "inhibit",
    "initial",
    "initiate",
    "injunction", "injunctive",
    "injure", "injured", "injury",
    "inmate",
    "innocent", "innocence",
    "inquiry",
    "insider",
    "insolvency", "insolvent",
    "inspect",
    "installment",
    "instrument",
    "instrumentality",
    "insubordination",
    "insufficient",
    "insurance", "insure", "insured", "insurer",
    "intangible",
    "intent", "intention", "intentional",
    "intercept",
    "interest",
    "interfere", "interference",
    "interim",
    "interlocutory",
    "intermediary",
    "interpleader",
    "interpret", "interpretation",
    "interrogate", "interrogation", "interrogatory",
    "interrupt",
    "intervene", "intervention",
    "intestate",
    "intimidate", "intimidation",
    "intoxicating",
    "intrude", "intrusion",
    "invade",
    "invalid", "invalidate",
    "invention",
    "invest", "investment",
    "investigate", "investigation", "investigator",
    "invoke",
    "involuntary",
    "involve",
    "issue",
    "item",
    "joinder",
    "joint",
    "judge", "judgment", "judgment creditor",
    "judgment debtor",
    "judicial", "judicial review",
    "judiciary",
    "jurat",
    "jurisdiction", "jurisdictional",
    "jurisprudence",
    "juror", "jury",
    "justice",
    "justification", "justify",
    "juvenile",
    "kidnapping",
    "landlord",
    "lapse",
    "latent",
    "law", "lawful", "lawfully",
    "lawsuit",
    "lawyer",
    "lease",
    "leave",
    "legatee",
    "legacy",
    "legal", "legality", "legalize", "legally",
    "legislate", "legislation", "legislative", "legislature",
    "legitimacy", "legitimate",
    "lend", "lender", "lending",
    "lessee", "lessor",
    "letter",
    "levy",
    "lewd",
    "liability", "liable",
    "libel", "libelous",
    "license", "licensee",
    "lien",
    "limit", "limitation",
    "liquidate", "liquidation", "liquidator",
    "litigant", "litigate", "litigation", "litigious",
    "loan",
    "lobby",
    "locus",
    "lodge",
    "malice", "malicious",
    "malpractice",
    "mandamus",
    "mandate", "mandatory",
    "manslaughter",
    "manufacture",
    "margin",
    "marital",
    "market",
    "material", "materiality",
    "matter",
    "maturity",
    "mediation", "mediator",
    "memorandum",
    "merger",
    "merit",
    "minor",
    "minority",
    "minute",
    "misappropriation",
    "miscarriage",
    "misconduct",
    "misdemeanor",
    "misrepresentation",
    "mistake", "mistaken",
    "mistrial",
    "mitigate", "mitigation",
    "modification", "modify",
    "molestation",
    "monitor",
    "monopoly",
    "moratorium",
    "mortgage", "mortgagee", "mortgagor",
    "motion",
    "murder",
    "mutual",
    "narcotic",
    "negate",
    "negative",
    "neglect", "negligence", "negligent",
    "negotiable", "negotiate", "negotiation",
    "nominal",
    "nominate", "nomination",
    "noncompete",
    "noncompliance",
    "nondisclosure",
    "nonperformance",
    "nonprofit",
    "notice",
    "notification", "notify",
    "notary",
    "notwithstanding",
    "novation",
    "nuisance",
    "null", "nullity", "nullify",
    "oath",
    "object", "objection", "objectionable",
    "obligate", "obligated", "obligation", "obligatory",
    "oblige",
    "obscene",
    "obstruct", "obstruction",
    "obtain",
    "offense", "offensive",
    "offer",
    "officer",
    "official",
    "omit",
    "opinion",
    "oppose", "opposition",
    "option",
    "order",
    "ordinance",
    "original",
    "outcome",
    "out-of-court",
    "overrule",
    "override",
    "overturn",
    "own",
    "owner", "ownership",
    "panel",
    "paralegal",
    "pardon",
    "parent",
    "parol",
    "parole",
    "partial",
    "participate",
    "partition",
    "partner", "partnership",
    "party",
    "patent",
    "paternity",
    "pay", "payment",
    "penal", "penalty",
    "pending",
    "per capita",
    "per curiam",
    "per se",
    "perfection",
    "performance",
    "peril",
    "perjury",
    "permanent",
    "permissible",
    "permission", "permissive", "permit",
    "perpetrate", "perpetrator",
    "perpetual",
    "personal",
    "personality",
    "personally",
    "personnel",
    "petition", "petitioner",
    "plaintiff",
    "plan",
    "plea", "plead", "pleading",
    "pledge",
    "police",
    "policy",
    "poll",
    "portion",
    "possession",
    "power",
    "practice",
    "preamble",
    "precede",
    "precedent",
    "preclude",
    "predatory",
    "predecessor",
    "preference",
    "prejudice", "prejudicial",
    "preliminary",
    "premise", "premises",
    "premium",
    "prerequisite",
    "prerogative",
    "prescribe", "prescription",
    "present",
    "presentment",
    "preside",
    "president",
    "presume", "presumption",
    "pretrial",
    "prevail",
    "prevent",
    "previous",
    "price",
    "primarily",
    "primary",
    "principal",
    "principle",
    "prior",
    "priority",
    "private",
    "privatization",
    "privilege", "privileged",
    "prize",
    "pro rate",
    "probable cause",
    "probate",
    "probation", "probation officer",
    "proceeding",
    "proceeds",
    "process", "process server",
    "produce",
    "product",
    "production",
    "profession",
    "professional",
    "profit",
    "prohibit", "prohibited", "prohibition", "prohibitory",
    "promise", "promissory",
    "promote",
    "proof",
    "property",
    "proposal", "propose",
    "proprietary",
    "prosecute", "prosecution", "prosecutor",
    "prospectus",
    "protect", "protection",
    "protest",
    "prove",
    "provide",
    "province",
    "provision", "provisional",
    "proxy",
    "prudent",
    "public",
    "publication",
    "publish",
    "purchase",
    "purport",
    "purpose",
    "pursuant",
    "pursue",
    "qualification", "qualified",
    "qualify",
    "quantum",
    "quash",
    "quasi",
    "question",
    "quiet title",
    "quit",
    "quitclaim",
    "quorum",
    "quota",
    "ratification", "ratify",
    "ratio",
    "reach",
    "read",
    "real",
    "real estate",
    "reasonable",
    "rebut", "rebuttal",
    "receipt",
    "receivable", "receive", "receiver", "receivership",
    "recital",
    "recognition",
    "recognize",
    "recommendation",
    "record", "recordation",
    "recoup",
    "recourse",
    "recover", "recovery",
    "redemption",
    "redress",
    "refer",
    "reference",
    "referendum",
    "referral",
    "reform",
    "refund",
    "refusal", "refuse",
    "register",
    "registrar",
    "registration",
    "regulate", "regulation", "regulatory",
    "rehabilitate", "rehabilitation",
    "rehearing",
    "reimburse", "reimbursement",
    "reins",
    "reinsurance",
    "reject",
    "relate",
    "release",
    "relevance", "relevant",
    "relief",
    "reliance",
    "relinquish",
    "remainder",
    "remand",
    "remedy", "remedies", "remedial",
    "remit",
    "removal", "remove",
    "render",
    "renegotiate",
    "renew", "renewal",
    "renounce",
    "rent",
    "reorganization",
    "repair",
    "repatriation",
    "repay", "repayment",
    "repeal",
    "replevin",
    "reply",
    "report",
    "represent", "representation", "representative",
    "reprieve",
    "reprimand",
    "reproduction",
    "repudiate", "repudiation",
    "reputation",
    "request",
    "require", "required", "requirement", "requisite",
    "rescind", "rescission",
    "reserve",
    "reside", "residence", "resident", "residential",
    "resignation",
    "resist",
    "resolution",
    "resolve",
    "resort",
    "resource",
    "respond", "respondent",
    "restitution",
    "restoration",
    "restrain", "restraint",
    "restrict", "restricted", "restriction", "restrictive",
    "restructure",
    "result",
    "resume",
    "retain", "retention",
    "retaliate", "retaliation",
    "retire", "retirement",
    "retract",
    "retroactive",
    "return",
    "revenue",
    "reverse", "reversible", "reversion", "revert",
    "review",
    "revise", "revision",
    "revive", "revival",
    "revocable", "revocation", "revoke",
    "right",
    "risk",
    "royalty",
    "rule", "ruling",
    "safeguard",
    "safety",
    "sale",
    "sanction",
    "satisfaction",
    "satisfy",
    "schedule",
    "scire facias",
    "seal",
    "search",
    "seat",
    "secure", "secured", "security",
    "securities",
    "segregate",
    "seize", "seizure",
    "select",
    "sentence",
    "separate",
    "sequester",
    "service",
    "servitude",
    "set aside",
    "setoff",
    "settle", "settled", "settlement",
    "severability",
    "several",
    "severally",
    "severance",
    "share",
    "shareholder",
    "sheriff",
    "sight",
    "sign", "signature",
    "signatory",
    "significance",
    "simple",
    "slander",
    "slavery",
    "slide",
    "sovereign",
    "sovereignty",
    "special",
    "specific",
    "specification",
    "specify",
    "stamp",
    "standard",
    "standing",
    "state",
    "statement",
    "status",
    "statute", "statute of limitations", "statutory",
    "stay",
    "stipulate", "stipulation",
    "stock",
    "strategy",
    "strict",
    "strictly",
    "strike",
    "subject",
    "sublease",
    "submission", "submit",
    "subordinate",
    "subpoena",
    "subscription",
    "subsequent",
    "subsidiary",
    "subsidize", "subsidy",
    "substantial",
    "substantiate",
    "substantive",
    "substitute",
    "subtenant",
    "sue",
    "suffice",
    "sufficient",
    "suit",
    "summary",
    "summon", "summons",
    "supersedeas",
    "supersede",
    "supervise", "supervision", "supervisor",
    "supplement",
    "supply",
    "support",
    "supra",
    "supreme",
    "surety",
    "surplus",
    "surrender",
    "survival",
    "survive",
    "suspect",
    "suspend", "suspension",
    "sustain",
    "swear", "sworn",
    "tax",
    "temporary",
    "tenancy", "tenant",
    "tender",
    "tenement",
    "term",
    "terminal",
    "terminate", "termination",
    "terms",
    "territory",
    "testament", "testamentary",
    "testator", "testatrix",
    "testify", "testimony",
    "theft",
    "third party",
    "title",
    "toll",
    "tort",
    "tortious",
    "trade",
    "trademark",
    "transaction",
    "transfer",
    "transferee",
    "transferor",
    "treason",
    "treasury",
    "treaty",
    "trespass",
    "trial",
    "tribunal",
    "trigger",
    "true",
    "trust", "trustee",
    "turnover",
    "ultimate",
    "ultra vires",
    "unanimous",
    "unavoidable",
    "unconscionable",
    "unconstitutional",
    "underwrite", "underwriter", "underwriting",
    "undue",
    "unfair",
    "unforeseen",
    "unified",
    "uniform",
    "unilateral",
    "union",
    "unit",
    "united",
    "unjust",
    "unlawful", "unlawfully",
    "unlicensed",
    "unliquidated",
    "unopposed",
    "unreasonable",
    "unresolved",
    "unsafe",
    "unsatisfied",
    "unsecured",
    "unsound",
    "unsworn",
    "unti",
    "use",
    "usury",
    "utility",
    "vacate",
    "valid", "validate", "validation", "validity",
    "valuation", "value",
    "variance",
    "vendor",
    "venue",
    "verdict",
    "verify", "verification",
    "versus",
    "vest", "vested",
    "veto",
    "violate", "violation",
    "void", "voidable",
    "voir dire",
    "voluntary",
    "vote",
    "wage",
    "waive", "waiver",
    "warrant", "warranty",
    "will", "willful",
    "witness",
    "writ",
    "write",
    "written",
    "wrong",
    "wrongful", "wrongfully",
    "yield",
})

CONSTRAINING_WORDS: frozenset[str] = frozenset({
    "allege", "alleged",
    "apprehend",
    "arrest",
    "bind",
    "coerce", "coercion",
    "commit", "committed",
    "compel",
    "comply", "compulsory",
    "confine", "confinement",
    "constrain", "constrained", "constraint",
    "detain",
    "deter",
    "disallow",
    "dismiss",
    "enjoin",
    "fine",
    "force",
    "forfeit",
    "forgo",
    "forbid", "forbidden",
    "illegal", "illegitimate",
    "imprison", "imprisonment",
    "incapacitate",
    "incarcerate",
    "injunction",
    "involuntary",
    "keep",
    "limit", "limitation", "limited",
    "mandate", "mandatory",
    "must",
    "obey",
    "obligate", "obligated", "obligation", "obligatory",
    "penalty", "penalize",
    "prevent",
    "probation",
    "prohibit", "prohibited", "prohibition", "prohibitive",
    "punish", "punishment", "punitive",
    "refrain",
    "regulate", "regulated", "regulation",
    "require", "required", "requirement",
    "restrain", "restrained", "restraint",
    "restrict", "restricted", "restriction", "restrictive",
    "sanction",
    "shall",
    "stipulate", "stipulation",
    "subject",
    "suspend",
})


class LoughranMcDonaldScorer(BaseSentimentModel):
    def __init__(
        self,
        positive_words: frozenset[str] | None = None,
        negative_words: frozenset[str] | None = None,
        uncertainty_words: frozenset[str] | None = None,
        litigious_words: frozenset[str] | None = None,
        constraining_words: frozenset[str] | None = None,
        remove_stopwords: bool = True,
    ) -> None:
        self.positive = positive_words if positive_words is not None else POSITIVE_WORDS
        self.negative = negative_words if negative_words is not None else NEGATIVE_WORDS
        self.uncertainty = uncertainty_words if uncertainty_words is not None else UNCERTAINTY_WORDS
        self.litigious = litigious_words if litigious_words is not None else LITIGIOUS_WORDS
        self.constraining = constraining_words if constraining_words is not None else CONSTRAINING_WORDS
        self.remove_stopwords = remove_stopwords
        self._word_pattern = re.compile(r"[a-z]+(?:'[a-z]+)?")

    def _tokenize(self, text: str) -> list[str]:
        return self._word_pattern.findall(text.lower())

    def score_texts(self, texts: Sequence[str]) -> pd.DataFrame:
        rows: list[dict] = []
        for text in texts:
            tokens = self._tokenize(text)
            if not tokens:
                rows.append({
                    "label": "neutral",
                    "score": 0.0,
                    "confidence": 0.0,
                    "positive_prob": 0.0,
                    "negative_prob": 0.0,
                    "neutral_prob": 1.0,
                })
                continue

            pos_count = sum(1 for t in tokens if t in self.positive)
            neg_count = sum(1 for t in tokens if t in self.negative)
            unc_count = sum(1 for t in tokens if t in self.uncertainty)
            total_matched = pos_count + neg_count
            total_tokens = len(tokens)

            if total_matched == 0:
                rows.append({
                    "label": "neutral",
                    "score": 0.0,
                    "confidence": 0.0,
                    "positive_prob": 0.0,
                    "negative_prob": 0.0,
                    "neutral_prob": 1.0,
                })
                continue

            net = (pos_count - neg_count) / total_matched
            score = float(np.tanh(net * 2.0))
            confidence = min(total_matched / max(total_tokens, 1) * 2.0, 1.0)
            pos_prob = pos_count / total_matched if total_matched > 0 else 0.0
            neg_prob = neg_count / total_matched if total_matched > 0 else 0.0
            neut_prob = 1.0 - (pos_prob + neg_prob)

            total_prob = pos_prob + neg_prob + neut_prob
            if abs(total_prob - 1.0) > 0.001:
                neut_prob += 1.0 - total_prob

            if score > 0.1:
                label = "positive"
            elif score < -0.1:
                label = "negative"
            else:
                label = "neutral"

            rows.append({
                "label": label,
                "score": round(score, 4),
                "confidence": round(confidence, 4),
                "positive_prob": round(pos_prob, 4),
                "negative_prob": round(neg_prob, 4),
                "neutral_prob": round(neut_prob, 4),
            })

        return pd.DataFrame(rows)
